### ISSUE TITLE
Certificate not valid

### ISSUE THREAD

**Issue by hovancik** [PacBSD/pacweb#11]
certificate is not valid for https://pacbsd.org

https://github.com/DiscoverBSD/awesome-bsd/issues/12

website also redirects to weird location for some users.

**Comment by vendion** [comment]
I can't help with the DiscoverBSD issue, but I let the cert expire as the project is currently inactive and everything in the repos is so old you probably shouldn't be running it. Thus the expired cert to try and discourage people using it.

If there is enough interest in others contributing the project then maybe we will revive the project.

**Comment by hovancik** [comment]
Good to know, thanks ;]

**Comment by markzz** [comment]
Now that I'm out of school and have some "real" time to work on things like this, I wanted to get back to it. I have to hand you an updated PGP key, but I'll get in touch on some changes I'd like to make soon.
