### ISSUE TITLE
pacbsd.org https certificate expired

### ISSUE THREAD

**Issue by ZNikke** [PacBSD/pacweb#13]
The certificate for https://pacbsd.org/ expired on 12 November 2018.

It seems to be a Lets Encrypt cert, so likely the certbot has stopped working without You noticing.

In addition to fix the cert, I would recommend at least a daily cron job that tries to access the site and complains if it fails so you catch this yourself as the error notification from certbot can be a bit lacking.

**Comment by markzz** [comment]
see #11
