### ISSUE TITLE
Cross-Site Access Issue With FontAwesome

### ISSUE THREAD

**Issue by markzz** [PacBSD/pacweb#5]
When visiting https://www.pacbsd.org/, there is an issue that all the included stylesheets and related files are being loaded from https://pacbsd.org/ which causes a cross-site access violation.

The main culprit is FontAwesome and causes the bullets on the sidebar to not load unless you visit the subdomainless url.

This is the error message from the Firefox console:
```
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:3): bad URI or cross-site access not allowed source: https://pacbsd.org/font/font-awesome/fonts/fontawesome-webfont.ttf?v=4.3.0
```

**Comment by vendion** [comment]
The main problem is the way hugo handles replacing `{{ .Site.BaseURL }}` when generating the site.

One way to work around this is to only allow web traffic from https://www.pacbsd.org or https://pacbsd.org and do a `HTTP 301` or similar in Nginx (or maybe setup a CNAME but that may be dumb) for the other that way links should still work and should resolve that issue.

I'm just not sure which one should be prefered.

**Comment by markzz** [comment]
Why not just make local paths relative?

**Comment by vendion** [comment]
It should be using relative paths now and accessing the site with and without the `www.` sub-domain doesn't cause a Cross-Site access problem.

The main reason the site was using the absolute path was that is what the base theme use us had and it was never changed.
